### ISSUE TITLE
attributes/value not loaded from dot

### ISSUE THREAD

**Issue by fundef1** [anvaka/ngraph.fromdot#1]
I noticed that only the structure of a .dot file is loaded into the graph, and not the data attributes/values. 
In the source there's a TODO confirming that. (also in the todot module node attributes weren't written out either)

any chance of you ticking that TODO of your list?

or in the meantime, any suggestions for storing(serializing) a graph and its values in txt format?
I don't particularly care for the .dot format, I have a graph generated via your library which I need to load into your library somewhere else.

thanks!

**Comment by anvaka** [comment]
you could use [ngraph.tojson](https://github.com/anvaka/ngraph.tojson) to store and [ngraph.fromjson](https://github.com/anvaka/ngraph.fromjson) to read back in the meantime.

**Comment by fundef1** [comment]
Perfect - to/fromjson is all I needed.
thanks again.
